### ISSUE TITLE
FileManager

### ISSUE THREAD

**Issue by felix4webscience** [bkrumnow/BotDetectionScanner#3]
Hi,

I tried to run the file_manager_test.py file. Unfortunately an error appears always according to FileManager.py.

It seems that the issue is raised because of the command in line 23 - 24:

`with open(os.path.join('/detection/configuration', 'config.json')) as json_data_file:
    config = json.load(json_data_file)`

=> 
`with open(os.path.join('/detection/configuration', 'config.json')) as json_data_file:
    IOError: [Errno 2] No such file directory: 'detection/configuration/config.json')`

for what ever reason the config.json file can not be found. I've double checked the directory and the json file is correct. Therefore I can not execute the Scanner.py. Is there anything I can do about it?

System:
OS: Ubuntu 16.04
IDE: PyCharmCommunity Edition 2019 (Terminal)

**Comment by bkrumnow** [comment]
This repo will not be developed further. Also tests will not.
